title: The state of the United States democracy 
author: nushlaywhyee
email: nushlaywhyee@bennington.edu
description: > # this means to ignore newlines until "baseurl:"
  Site for The state of the United States democracy , Bennington College, Fall 2016
# baseurl: "/minima"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
